SpaApp/urls.py
from django.urls import path, reverse_lazy
from .views import *

urlpatterns = [
    path('', MainPage.as_view(), name='main_page'),
    path('service/<int:pk>/', ServicesDetail.as_view(), name='service_detail'),
    path('price', PricePage.as_view(), name='price'),
    path('masters', MasterPage.as_view(), name='master_page'),
    path('contacts', ContactsPage.as_view(), name='contacts_page'),
    path('book/<int:pk>/', BookingObject.as_view(), name='book_service'),
    path('confirmation', BookingConfirmation.as_view(), name='confirmation'),
]

SpaCentr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from SpaCentr import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('users.urls')),
    path('', include('SpaApp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('registration', SignUpView.as_view(), name='registrations'),
    path('logout', LogoutView.as_view(next_page=reverse_lazy('main_page')), name='logout'),
    path('login', LoginUser.as_view(), name='login')
]

SpaApp/models.py
from django.db import models
from django.urls import reverse


class Masters(models.Model):
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото', blank=True)
    surname = models.CharField(max_length=100, verbose_name="Фамилия")
    name = models.CharField(max_length=100, verbose_name="Имя")
    middlename = models.CharField(max_length=100, verbose_name="Отчество", blank=True)
    FIO = models.CharField(max_length=255, verbose_name='ФИО')
    services = models.ManyToManyField('Services', related_name='specialists')

    def __str__(self):
        return self.FIO

    class Meta:
        verbose_name = 'Мастер'
        verbose_name_plural = 'Мастера'


class Services(models.Model):
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото', blank=True)
    title = models.CharField(max_length=150, verbose_name='Название услуги')
    description = models.TextField(verbose_name='Описание услуги')
    duration = models.CharField(max_length=150, verbose_name='Длительность услуги')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'

    def get_absolute_url(self):
        return reverse("service_detail", kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        self.title = self.title.lower()
        super(Services, self).save(*args, **kwargs)


class TimeSlot(models.Model):
    time = models.DateTimeField(verbose_name='Дата и время бронирования')
    is_available = models.BooleanField(default=True, verbose_name='Статус')

    def __str__(self):
        return str(self.time)

    class Meta:
        verbose_name = 'Время бронирования'
        verbose_name_plural = 'Время бронирования'


class Booking(models.Model):
    service = models.ForeignKey(Services, on_delete=models.CASCADE, verbose_name='Услуга для бронирования')
    time_slot = models.ForeignKey(TimeSlot, on_delete=models.CASCADE, verbose_name='Время бронирования')
    client_name = models.CharField(max_length=255, verbose_name='Клиент')
    masters = models.ForeignKey(Masters, on_delete=models.CASCADE, verbose_name='Мастер')

    def __str__(self):
        return self.client_name

    class Meta:
        verbose_name = 'Бронь'
        verbose_name_plural = 'Бронь'

SpaApp/forms.py
from datetime import datetime, timedelta

from bootstrap_datepicker_plus.widgets import DatePickerInput, TimePickerInput, DateTimePickerInput, MonthPickerInput, \
    YearPickerInput
from django import forms
from .models import TimeSlot, Masters


class DateTimeForm(forms.ModelForm):
    master = forms.ModelChoiceField(queryset=Masters.objects.all(), label='Мастер')

    def __init__(self, *args, **kwargs):
        masters = kwargs.pop('masters', None)
        super().__init__(*args, **kwargs)
        if masters:
            self.fields['master'].queryset = masters

    class Meta:
        model = TimeSlot
        fields = ['time', 'master']

        widgets = {
            'time': DateTimePickerInput(options={
                "showTodayButton": True,
                "locale": "ru",
                "format": "DD.MM.YYYY: HH:mm",
                'minDate': (datetime.today() + timedelta(days=1)).strftime('%Y-%m-%d 00:00:00'),
                # 'maxDate': (datetime.today() + timedelta(days=2)).strftime('%Y-%m-%d 23:59:59'),
                'enabledHours': [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

            })
        }

SpaApp/views.py
from django.shortcuts import render, redirect
from .models import *
from django.views.generic import TemplateView, ListView, DetailView
from django.db.models.functions import Lower
from .forms import DateTimeForm

class MainPage(ListView):
    template_name = 'SpaApp/MainPage.html'
    model = Services
    context_object_name = 'services'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title_contains_query'] = self.request.GET.get('title_contains')
        if context['title_contains_query'] != None and context['title_contains_query'] != '':
            context['products_data'] = Services.objects.filter(title__icontains=context['title_contains_query'].lower())
        else:
            context['products_data'] = Services.objects.all().order_by('-pk')
        return context

    def get_queryset(self):
        return Services.objects.all().order_by('-pk')


class ServicesDetail(DetailView):
    model = Services
    template_name = 'SpaApp/ProductPage.html'
    context_object_name = 'service'


class PricePage(ListView):
    template_name = 'SpaApp/PricePage.html'
    model = Services
    context_object_name = 'services'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title_contains_query'] = self.request.GET.get('title_contains')
        if context['title_contains_query'] != None and context['title_contains_query'] != '':
            context['products_data'] = Services.objects.filter(title__icontains=context['title_contains_query'].lower())
        else:
            context['products_data'] = Services.objects.all().order_by('-pk')
        return context


class MasterPage(ListView):
    template_name = 'SpaApp/MastersPage.html'
    model = Masters
    context_object_name = 'masters'

    def get_queryset(self):
        return Masters.objects.all().order_by('-pk')

class ContactsPage(TemplateView):
    template_name = 'SpaApp/Contacts.html'


class BookingObject(DetailView):
    model = Services
    template_name = 'SpaApp/BookingService.html'
    context_object_name = 'service'
    form_class = DateTimeForm  # Добавляем кастомную форму

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        service = self.get_object()
        masters = service.specialists.all()
        print(masters)
        context['form'] = DateTimeForm(masters=masters)  # Добавляем форму в контекст
        return context

    def post(self, request, pk):
        if request.method == 'POST':
            form = DateTimeForm(request.POST)
            if form.is_valid():
                time_slot = TimeSlot.objects.create(time=form.cleaned_data['time'])
                master = form.cleaned_data['master']
                print(master)
                booking = Booking.objects.create(service=self.get_object(), time_slot=time_slot,
                                                 client_name=request.user, masters=master)
                return redirect('confirmation')
            else:
                form = DateTimeForm()
                return redirect('main_page')


class BookingConfirmation(TemplateView):
    template_name = 'SpaApp/BookingConfirmation.html'

SpaApp/templates/SpaApp/AddProductPage.html
{%extends 'base_layout.html' %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/add_product.css' %}">
{% endblock %}

{% block title %}Добавление продукта{% endblock %}

{% block header %}
{% include 'GGsApp/header.html' %}
{% endblock %}

{% block content %}
<div class="addProduct__conainer _container">
    <div class="addProduct__title"><h2>Добавление товара</h2></div>
    <div class="addProduct__form">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for f in form %}
            <div class="form__data">
                <div class="form__label">
                    <label class="label__form" for="{{f.id_for_label}}">{{f.label}}:</label>
                </div>
                <div class="form__form">{{f}}</div>
            </div>
            {% endfor %}
            <div class="addProduct__button">
                <button class="button__form" type="submit">Добавить</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

SpaApp/templates/SpaApp/BookingConfirmation.html
{%extends 'base_layout.html' %}
{% load static %}
{% load humanize %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/BookingService.css' %}">
{% endblock %}

{% block header %}
{% include 'SpaApp/header.html' %}
{% endblock %}

{% block content %}
<div class="booking__container _container">
    <div class="main__header">
        <div class="main__info info-main">
            <div class="info-main__phone">
                <div class="phone__data">Тел: <a href="tel:+79570000001" class="phone__link">+7 957 000 00 01</a></div>
            </div>
            <div class="info-main__mail">
                <div class="mail__data">Mail: <a href="mailto:SpaLola116@mail.ru"
                                                 class="mail_link">SpaLola116@mail.ru</a></div>
            </div>
        </div>
    </div>
    <div class="confirmation__title">
        Ваша заявка подтверждена!
    </div>
</div>
{% endblock %}

SpaApp/templates/SpaApp/BookingService.html
{%extends 'base_layout.html' %}
{% load static %}
{% load humanize %}
{% block styles %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<link rel="stylesheet" href="{% static 'css/BookingService.css' %}">
<style>
    /* Обнуление стилей */
*{
  padding: 0;
  margin: 0;
  border: 0;
}


*,*:before,*:after {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}


:focus,:active {
  outline: none;
}
a:focus,a:active {
  outline: none;
}


nav,
footer,header,aside {
  display: block;
}


html,body {
  height: 100%;
  width: 100%;
  font-size: 100%;
  line-height: 1;
  font-size: 14px;
  color: #252B42;
  font-weight: 500;
  font-family: "REX";
  -ms-text-size-adjust: 100%;
  -moz-text-size-adjust: 100%;
  -webkit-text-size-adjust: 100%;
}


input,button,textarea {
  font-family: inherit;
}


input::-ms-clear {
  display: none;
}
button {
  cursor: pointer;
}
button::-moz-focus-inner {
  padding: 0;
  border: 0;
}
a,
a:visited {
  text-decoration: none;
}
a:hover {
  text-decoration: none;
}
ul li {
  list-style: none;
}
img {
  vertical-align: top;
}
h1,h2,h3,h4,h5,h6 {
  font-size: inherit;
  font-weight: 400;
}
/* Технический класс*/
.wrapper{
  min-height: 100%;
  overflow: hidden;
  display: flex;
  flex-direction: column;
}
._container{
  max-width: 1100px;
  padding: 0 15px;
  margin: 0 auto;
}
@media (max-width: 790px){
  ._container{
    max-width: 100%;
    padding: 0 5px;
  }
}
body {
    font-family: 'Roboto', sans-serif;
    background: #b4947d;
}

/* HEADER */
.header {


}
.header__container {
  display: flex;
  flex-direction: column;

}
.header__body {
  background: #b4947d;
  width: 280px;
  height: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  position: fixed;
  transition: all 0.2s ease 0s;
  overflow-y: auto;
    border-right: 1.5px solid rgba(255, 255, 255, 1);

}
.header__body.active{
  left: 0;
  width: 100%;
  position: fixed;
  z-index: 100;
  overflow-y: auto;
}
@media (max-width: 900px){
  .header__body{
    position: fixed;
    left: -295px;
    height: 100vh;
  }
  .header__burger{
    left: 310px;
  }
}

.header__logo {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  padding: 10px 0;
  border-bottom: 1.5px solid rgba(255, 255, 255, 1);
  width: 100%;
}
.title__logo{
    color: white;
    font-size: 20px;
}
.header__burger{
  display: none;
}
@media(max-width: 900px){
 .header__burger {
    display: block;
    position: fixed;
    width: 40px;
    height: 20px;
    z-index: 10;
    padding: 20px;
    left: 15px;
    margin-top: 10px;
    margin-left: 0;



  }
  .header__burger span {
    position: absolute;
    background-color: white;
    left: 0;
    align-items: flex-start;
    justify-content: flex-start;
    width: 100%;
    height: 3px;
    top: 25px;
  }
  .header__burger:before,
  .header__burger:after{
    content: '';
    background-color: white;
    position: absolute;
    width: 100%;
    height: 3px;
    left: 0;
    transition: all 0.3s ease 0s;
   }
   .header__burger:before{
    top: 15px;
   }
   .header__burger:after{
    bottom: 2px;
   }
   .header__burger.active{
    position: fixed;
    left: 15px;
    top: 0;

   }
   .header__burger.active:before{
    transform: rotate(45deg);
    top: 21px;
   }
   .header__burger.active:after{
    transform: rotate(-45deg);
    bottom: 16px;
   }
   .header__burger.active span {
    transform: scale(0);
   }
}
.header__profile {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 10px 30px;
  border: 2px solid rgba(243, 225, 205, 1);
  margin: 10px 0;
  background: rgba(203, 169, 162, 1);
  border-image-slice: 1;

}
.profile {
}
.profile__photo {
  margin: -10px 0 10px 0 ;
}
.profile__name {
  margin: 5px 0 10px 0;
  font-weight: 600;
  font-size: 18px;
  line-height: calc(18/20*100%);
}
.profile__items {
  padding: 5px 0;
}
.profile__link{
  color: white;
}
.header__menu {
  background: #b4947d;
  position: relative;
  display: flex;
  margin: 5px 0 0 0;
  flex-direction: column;
  align-items: flex-start;
  text-align: left;
  padding: 0 25px 0 25px;
  width: 100%;
  height: 100%;
}
.header__menu.active{
  padding: 5px 25px 25px 25px;
}
.menu {

}
.menu__list {
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
}
.menu__item {
  padding: 2px 10px;
  width: 100%;
  display: flex;
}
.menu__item.active{
  justify-content: center;
  text-align: left;
  padding: 5px 35px 5px 0;
}
.menu__item:hover {
  background: rgba(203, 169, 162, 1);
  border-radius: 11px;
  cursor: pointer;
}
.menu__link {
  color: white;
  padding: 10px 0 10px 5px;
  font-weight: 600;
  font-size: 18px;
  line-height: calc(18/22*100%);
}
button.menu__link{
    background: none;
}
.menu__icon {
}
.menu__icon img{
  padding: 5px;
}
.logout_item{
 margin-top: auto;
}


.main{
  padding: 20px 20px 20px 20px;
  margin-left: 270px;
  color: white;
}

@media(max-width: 900px){
  .main{
    margin-left: 30px;
  }
}


/* modal  */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  padding-top: 200px; /* Location of the box */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content */
.modal-content {
  background-color: #1E2653;
  margin: auto;
  padding: 20px;
  border: 1px solid #888;
  max-width: 600px;
  display: flex;
  justify-content: center;
  color: white;
}
.modal__text{
    display: block;
    padding: 10px;
}
/* The Close Button */
.close {
  color: #aaaaaa;
  font-size: 28px;
  font-weight: bold;
  padding: 10px 10px 10px 40px;;

}

.close:hover,
.close:focus {
  color: white;
  text-decoration: none;
  cursor: pointer;
}

.main__header{
    display: flex;
    justify-content: flex-end;
}
.main__info{
    display: flex;
    padding: 15px;
}

.info-main{

}
.info-main__phone{
    padding: 0 20px;
}
.phone__data{
    color: white;
    font-size: 16px;

}
.phone__link{
    color: white;
    font-size: 16px;
}
.phone__link:hover{
    text-decoration: underline;
}

.info-main__mail{
    padding: 0 20px;
}
.mail__data{
    color: white;
    font-size: 16px;
}
.mail_link{
    color: white;
    font-size: 16px;
}
.mail_link:hover{
    text-decoration: underline;
}
input#id_time{
    padding: 5px;
}
select#id_master {
    max-width: 210px;
    height: 20px;
}

</style>
{% endblock %}

{% block title %}Цены{% endblock %}

{% block header %}
{% include 'SpaApp/header.html' %}
{% endblock %}


{% block content %}
<div class="booking__container _container">
    <div class="main__header">
        <div class="main__info info-main">
            <div class="info-main__phone">
                <div class="phone__data">Тел: <a href="tel:+79570000001" class="phone__link">+7 957 000 00 01</a></div>
            </div>
            <div class="info-main__mail">
                <div class="mail__data">Mail: <a href="mailto:SpaLola116@mail.ru"
                                                 class="mail_link">SpaLola116@mail.ru</a></div>
            </div>
        </div>
    </div>
    <div class="booking__body">
        <div class="booking__title">Бронирование услуги: {{service.title}}</div>
        <div class="booking__form">
            <form method="post">
                {% csrf_token %}

                <div class="form">
                    {{ form.media }}
                    {{ form }}

                    <button class="booking__button" type="submit">Забронировать</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

SpaApp/templates/SpaApp/Contacts.html
{%extends 'base_layout.html' %}
{% load static %}

{% block styles %}


<link rel="stylesheet" href="{% static 'css/contacts.css' %}">
{% endblock %}

{% block title %}Цены{% endblock %}

{% block header %}
{% include 'SpaApp/header.html' %}
{% endblock %}

{% block content %}
<div class="main__conainer _container">
    <div class="main__header">
        <div class="main__info info-main">
            <div class="info-main__phone">
                <div class="phone__data">Тел: <a href="tel:+79570000001" class="phone__link">+7 957 000 00 01</a></div>
            </div>
            <div class="info-main__mail">
                <div class="mail__data">Mail: <a href="mailto:SpaLola116@mail.ru"
                                                 class="mail_link">SpaLola116@mail.ru</a></div>
            </div>
        </div>
    </div>
    <div class="main__body contacts">
        <div class="contact__info">
            <div class="info__phone">Тел: <a href="tel:+79570000001" class="phone__link">+7 957 000 00 01</a></div>
            <div class="info__mail">Mail: <a href="mailto:SpaLola116@mail.ru" class="mail_link">SpaLola116@mail.ru</a>
            </div>
            <div class="info__vk">ВК:</div>
            <div class="info__tg">Телеграмм:</div>
            <div class="info__address">Адрес:</div>
        </div>
        <div class="contact__photo">
            <img src="{% static 'image/qr.png' %}" alt="">
        </div>
    </div>
</div>
{% endblock %}

SpaApp/templates/SpaApp/MainPage.html
{%extends 'base_layout.html' %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/MainPage.css' %}">
{% endblock %}

{% block title %}Главная страница{% endblock %}

{% block header %}
{% include 'SpaApp/header.html' %}
{% endblock %}

{% block content %}
<div class="main__conainer _container">
    <div class="main__header">
        <div class="main__search">
            <form method="get" action="">
                {% if title_contains_query %}
                <input type="search" autocomplete="off" class="search" value="{{title_contains_query}}" name="title_contains" placeholder="Поиск">
                {% else %}
                <input type="search" autocomplete="off" class="search" name="title_contains" placeholder="Поиск">
                {% endif %}
            </form>
        </div>
        <div class="main__info info-main">
            <div class="info-main__phone">
                <div class="phone__data">Тел: <a href="tel:+79570000001" class="phone__link">+7 957 000 00 01</a></div>
            </div>
            <div class="info-main__mail">
                <div class="mail__data">Mail: <a href="mailto:SpaLola116@mail.ru" class="mail_link">SpaLola116@mail.ru</a></div>
            </div>
        </div>
    </div>
    <div class="main__body">
        <div class="main__row">
            {% for service in products_data %}
            <div class="main__column">
                <div class="main__item item">
                    <div class="item__image">
                        {% if service.photo %}
                        <img src="{{service.photo.url}}" alt="service_image">
                        {% else %}
                        <img src="" alt="NoneImage">
                        {%endif%}
                    </div>
                    <div class="item__border-text">
                        <div class="item__title">
                            <a class="title__link" href="{{service.get_absolute_url}}">{{service.title|upper }}</a>
                        </div>
                        <div class="item__body">
                            <div class="item__marketplace">
                                <a href="{{service.get_absolute_url}}" class="marketpalce__link">Подробнее</a>
                            </div>
                            <div class="item__type">
                                <a href="#" class="type__link">В корзину</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {%endfor%}
        </div>
    </div>
</div>
{% endblock %}

SpaApp/templates/SpaApp/MastersPage.html
{%extends 'base_layout.html' %}
{% load static %}

{% block styles %}


<link rel="stylesheet" href="{% static 'css/masterspage.css' %}">
{% endblock %}

{% block title %}Цены{% endblock %}

{% block header %}
{% include 'SpaApp/header.html' %}
{% endblock %}

{% block content %}
<div class="main__conainer _container">
    <div class="main__header">
        <div class="main__info info-main">
            <div class="info-main__phone">
                <div class="phone__data">Тел: <a href="tel:+79570000001" class="phone__link">+7 957 000 00 01</a></div>
            </div>
            <div class="info-main__mail">
                <div class="mail__data">Mail: <a href="mailto:SpaLola116@mail.ru"
                                                 class="mail_link">SpaLola116@mail.ru</a></div>
            </div>
        </div>
    </div>
    <div class="main__body">
        <div class="body__row">
            {% for master in masters %}
            <div class="body__column">
                <div class="body__item item-main">
                    <div class="item-main__photo">
                        {% if master.photo %}
                        <img src="{{master.photo.url}}" alt="master_photo">
                        {% else %}
                        <img src="" alt="NoneImage">
                        {%endif%}
                    </div>
                    <div class="item-main__services">
                        {% for service in master.services.all %}
                        {{ service.title|upper}}
                        {% endfor %}
                    </div>
                    <div class="item-main__fio">
                        {{master.FIO}}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

SpaApp/templates/SpaApp/PricePage.html
{%extends 'base_layout.html' %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/MainPage.css' %}">
<link rel="stylesheet" href="{% static 'css/pricepage.css' %}">
{% endblock %}

{% block title %}Цены{% endblock %}

{% block header %}
{% include 'SpaApp/header.html' %}
{% endblock %}

{% block content %}
<div class="main__conainer _container">
    <div class="main__header">
        <div class="main__search">
            <form method="get" action="">
                {% if title_contains_query %}
                <input type="search" autocomplete="off" class="search" value="{{title_contains_query}}"
                       name="title_contains" placeholder="Поиск">
                {% else %}
                <input type="search" autocomplete="off" class="search" name="title_contains" placeholder="Поиск">
                {% endif %}
            </form>
        </div>
        <div class="main__info info-main">
            <div class="info-main__phone">
                <div class="phone__data">Тел: <a href="tel:+79570000001" class="phone__link">+7 957 000 00 01</a></div>
            </div>
            <div class="info-main__mail">
                <div class="mail__data">Mail: <a href="mailto:SpaLola116@mail.ru" class="mail_link">SpaLola116@mail.ru</a></div>
            </div>
        </div>
    </div>

    <div class="price__body">
        <table>
            <thead>
            <tr>
                <th>Название</th>
                <th>Описание</th>
                <th>Длительность</th>
                <th>Цена</th>
            </tr>
            </thead>
            <tbody>
            {% for service in products_data %}
            <tr>
                <td>{{service.title}}</td>
                <td>{{service.description}}</td>
                <td class="description">{{service.duration}}</td>
                <td>{{service.price}} руб</td>

            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

SpaApp/templates/SpaApp/ProductPage.html
{%extends 'base_layout.html' %}
{% load static %}
{% load humanize %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/ProductPage.css' %}">
{% endblock %}

{% block title %}{{title}}{% endblock %}

{% block content %}
<div class="main__conainer _container">
    <div class="main__header">
        <div class="main__info info-main">
            <div class="info-main__phone">
                <div class="phone__data">Тел: <a href="tel:+79570000001" class="phone__link">+7 957 000 00 01</a></div>
            </div>
            <div class="info-main__mail">
                <div class="mail__data">Mail: <a href="mailto:SpaLola116@mail.ru" class="mail_link">SpaLola116@mail.ru</a></div>
            </div>
        </div>
    </div>
    <div class="main__body">
        <div class="body__title">{{service.title}}</div>
        <div class="body__row">
            <div class="body__photo">
                <img src="{{service.photo.url}}" alt="service_image">
            </div>
            <div class="body__text">
                {{service.description}}
            </div>
        </div>
        <div class="body__buttons">
            {% if user.is_authenticated %}
            <div class="body__button">
                <a href="{% url 'book_service' pk=object.pk%}" class="button__link">Записаться</a>
            </div>
            {% else %}
            <div class="body__button disabled">
                <a href="" class="button__link disabled">Записаться</a>
            </div>
            {% endif %}
            <div class="body__price">
                {{service.price|floatformat:0|intcomma}} руб/час
            </div>
        </div>


    </div>

</div>
{% endblock %}

{% block header %}
{% include 'SpaApp/header.html' %}
{% endblock %}